services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command:  sh -c "echo 'Esperando o banco de dados...'; sleep 10;
      echo 'Banco de dados disponível!'; 
      npx prisma migrate dev;
      npx prisma generate;
      npm run dev"
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app-backend
      - /app-backend/node_modules
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      TZ: 'America/Sao_Paulo'
    env_file:
      - .env
  
    volumes:
      - db-data:/var/lib/postgresql/data 
  
volumes:
  db-data: