services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "sleep 5 && npx prisma migrate dev --name create_drivers_table && npm run seed && npm run dev"
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app-backend
      - /app-backend/node_modules
    depends_on:
      - db
    env_file:
      - .env.docker
   

  db:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    env_file:
      - .env.docker
  
    volumes:
      - db-data:/var/lib/postgresql/data 
  
volumes:
  db-data: