services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app-backend
      - /app-backend/node_modules
    depends_on:
      - db
    env_file:
      - .env
   

  db:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
  
    volumes:
      - db-data:/var/lib/postgresql/data 
  
volumes:
  db-data: