services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npx prisma migrate deploy && npm run start"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TZ=America/Sao_Paulo
    env_file:
      - .env
  frontend:
    build: 
     context: ./frontend
     dockerfile: Dockerfile
    command: sh -c "npm run preview"
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - .env
  db:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment: 
      TZ: America/Sao_Paulo
      POSTGRESQL_TIMEZONE: America/Sao_Paulo
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: appTaxi
      DATABASE_URL: postgresql://postgres:postgres@db:5432/appTaxi
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 8s
      retries: 3
    volumes:
      - ./db-data:/bitnami/postgresql 
  
volumes:
  db-data: