services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "npx prisma migrate deploy && node dist/server.js"
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app-backend
      - /app-backend/node_modules
    depends_on:
      - db
    environment:
      - TZ=America/Sao_Paulo
    env_file:
      - .env
  db:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment: 
      TZ: America/Sao_Paulo
      POSTGRESQL_TIMEZONE: America/Sao_Paulo
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: appTaxi
      DATABASE_URL: postgresql://postgres:postgres@db:5432/appTaxi
    volumes:
      - ./db-data:/bitnami/postgresql 
  
volumes:
  db-data: